steps:
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/passing-task-387222/packer:1.7.8', '.' ]
- name: 'gcr.io/cloud-builders/gke-deploy'
  args: 
    - run
    - --filename=restaurantservice-deployment.yaml
    - --image=gcr.io/passing-task-387222/packer:1.7.8
    - --location=australia-southeast1
    - --cluster=cluster2
  


