steps:
  # Build and deploy Docker Compose services
  - name: "gcr.io/cloud-builders/docker-compose"
    args: ["up", "-d"]
    timeout: 1800s
    dir: /workspace

  # Run tests or perform additional checks
  - name: "gcr.io/cloud-builders/docker-compose"
    args: ["exec", "restaurantservice", "npm", "test"]
    dir: /workspace

  # Push Docker Compose services to a registry
  - name: "gcr.io/cloud-builders/docker-compose"
    args: ["push"]
    dir: /workspace
